### ISSUE TITLE
HTML compiler not exporting individual index.html files 

### ISSUE THREAD

**Issue by stevenanthonyrevo** [tylerhall/Roland#6]
@tylerhall 

Awesome work!

I tried out this on mac os 10.15 and had an issue with rendering the HTML files. 

Looking at the source, I found I didn't have Pygments installed, however, this didn't resolve the issue. 
  
```
pip install Pygments==2.6.1
```

https://github.com/tylerhall/Roland/blob/863897468a0682cf1bd5ace69d27e2fb532d2b87/roland/Objects/Website.swift#L69

Also found an error while running the command `roland` in the example repository. 

```
Error: Template is not accessible ../sample-roland/_templates/Atom.php
```
Is this a missing file and is this related to no `*.hmtl` files being exported after running the generator? 

Thank you! Happy Coding!

**Comment by tylerhall** [comment]
Thanks for that, @stevenanthonyrevo. The sample project was indeed missing the Atom (and Sitemap) templates. I've pushed those to the repo. I also ran `roland` in the sample project and was able to generate the site successfully. Let me know if you run into any other issues.

**Comment by stevenanthonyrevo** [comment]
@tylerhall Perfect! That resolves the issue, I will post the ending trail below. 

```
CREATED #52 (8 remaining): ../sample-roland/_www/category/open-source/index.html
CREATED #53 (7 remaining): ../sample-roland/_www/2020/02/index.html
---------
Finished!
---------

Rendered 59 pages in 14.72673499584198 seconds.
```
Nice 👍 , I didn't see that output before, Thank you!
